package com.example.namequiz;

public class QuestionAnswers {
    public static String question[] = {
            "What is the country of origin of the name Thiam?",
            "What is the country of origin of the name Santos?",
            "What is the country of origin of the name Zhang?",
            "What is the country of origin of the name Nilsson?",
            "What is the country of origin of the name Khumalo?",
            "What is the country of origin of the name Yoon?",
            "What is the country of origin of the name Hoffman?",
            "What is the country of origin of the name Yamaguchi?",
            "What is the country of origin of the name Smith?",
            "What is the country of origin of the name Ivanov?",
            "What is the country of origin of the name Mwangi?",
            "What is the country of origin of the name Murphy?",
            "What is the country of origin of the name Singh?",
            "What is the country of origin of the name Thamrong?",
            "What is the country of origin of the name Khachatryan?",
            "What is the country of origin of the name Flores?",
            "What is the country of origin of the name Moretti?",
            "What is the country of origin of the name Moyo?",
            "What is the country of origin of the name Kennedy?",
            "What is the country of origin of the name Addo?",
            "What is the country of origin of the name Miller?",
            "What is the country of origin of the name Papadopoulos?",
            "What is the country of origin of the name Cho?",
            "What is the country of origin of the name Wanjiru?",
            "What is the country of origin of the name Nguyen?",
            "What is the country of origin of the name Adewumi?",
    };
    public static String choices[][] = {
            {"Thailand", "Senegal", "Greece", "Spain"},
            {"Spain", "Egypt", "Cuba", "Laos"},
            {"South Korea", "Lesotho", "China", "Singapore"},
            {"Germany", "Sweden", "Australia", "Eritrea"},
            {"South Africa", "Guatemala", "Nigeria", "Honduras"},
            {"South Korea", "Thailand", "Japan", "Cambodia"},
            {"Scotland", "Germany", "England", "Italy"},
            {"Chad", "Japan", "Bulgaria", "Hong Kong"},
            {"Ireland", "England", "Finland", "Spain"},
            {"Portugal", "Russia", "Indonesia", "Tanzania"},
            {"Kenya", "Ghana", "Ethiopia", "Zimbabwe"},
            {"Finland", "Scotland", "Ireland", "Türkiye"},
            {"Egypt", "India", "Vietnam", "Iran"},
            {"India", "The Philippines", "Thailand", "Cambodia"},
            {"Armenia", "Thailand", "Greece", "Zimbabwe"},
            {"Norway", "Spain", "Belize", "South Africa"},
            {"Hungary", "Benin", "Slovakia", "Italy"},
            {"Egypt", "Zimbabwe", "Japan", "South Africa"},
            {"Scotland", "Ireland", "England", "Switzerland"},
            {"Ghana", "Sweden", "Pakistan", "Kenya"},
            {"Sweden", "England", "Ukraine", "Malta"},
            {"India", "Hawaii", "Greece", "Panama"},
            {"Senegal", "Japan", "Luo", "South Korea"},
            {"Japan", "Kenya", "Bangladesh", "Indonesia"},
            {"Lebanon", "Vietnam", "Cambodia", "Mongolia"},
            {"Ghana", "Moldova", "Nigeria", " Poland "},
    };
    public static String correctAnswers[] = {
            "Senegal", "Spain", "China", "Sweden", "South Africa", "South Korea", "Germany", "Japan", "England", "Russia", "Kenya", "Ireland", "India", "Thailand", "Armenia", "Spain", "Italy", "Zimbabwe", "Ireland", "Ghana", "England", "Greece", "South Korea", "Kenya", "Vietnam","Nigeria"
    };
}