name: flutterpr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.0
  shared_preferences: ^2.2.3
  photo_view: ^0.14.0
  http: ^1.2.1
  audio_video_progress_bar: ^2.0.3
  just_audio: ^0.9.39
  provider: ^6.0.0
  path: ^1.8.0
  location: ^7.0.0
  sensors_plus: ^1.0.0
  sqflite: ^2.3.3+1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  permission_handler: ^10.2.0
  flutter_lints: ^3.0.0
  test: ^1.20.0


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: CustomFont
      fonts:
        - asset: fonts/FuturaPTCondMedium.otf
          weight: 400
